eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8082
spring:
  application:
    name: client-common
  datasource:
    name: test
    password: wrewtrtr

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
