spring:
  application:
    name: stdmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual  # 手动确认ack
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual

server:
  port: 8080
